### PR TITLE
Added instructions about #duct/resource

### PR DESCRIPTION
**Pull request by mjmeintjes**

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks! Can you squash your commits?

**Comment by mjmeintjes** [comment]
Not sure how to do that, as I just edited the file on Github. I can redo the changes in a new pull request with only 1 commit?

**Comment by weavejester** [comment]
You could redo the PR. You could also pull the `patch-1` branch, rebase and force push it. Whatever's easiest :)

**Comment by isker** [comment]
@weavejester would you consider merging this as-is?  The instructions in it are quite helpful.

**Comment by weavejester** [comment]
Fixed by 0bdfc48

**Pull request closed without merging**
